---
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "truffleruby"]
    name: Verify on ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libphonenumber-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Compile
        run: bundle exec rake compile

      - name: RSpec
        run: bundle exec rspec --format RSpec::Github::Formatter --format documentation

      - name: Rubocop
        run: bundle exec rubocop --format github
