---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies (system)
        run: sudo apt-get -yqq install libphonenumber-dev

      - name: Install dependencies (ruby)
        run: gem install bundler && bundle install --jobs 4 --retry 3

      - name: Login
        run: |
          mkdir -p ~/.gem

          cat << EOF > ~/.gem/credentials
          ---
          :github: ${GITHUB_AUTH_TOKEN}
          :rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}
          EOF

          chmod 0600 ~/.gem/credentials
        env:
          GITHUB_AUTH_TOKEN: "Bearer ${{secrets.GITHUB_TOKEN}}"
          RUBYGEMS_AUTH_TOKEN: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
          OWNER: ${{ github.repository_owner }}

      - name: 🛳 Ship it
        run: |
          bundle exec rake publish:non_native
