---
name: Release

on: push

# on:
#   push:
#     tags:
#       - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7"]
        os: [ubuntu-latest, macos-latest]
    name: ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies (system)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get -yqq install libphonenumber-dev

      - name: Install dependencies (system)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install --build-from-source libphonenumber && brew link libphonenumber

      - name: Install dependencies (ruby)
        run: gem install bundler && bundle install --jobs 4 --retry 3

      - name: Compile
        run: bundle exec rake native gem

      - name: Publish
        run: ls pkg/*.gem
